app/quiz/forms.py
from flask_wtf import Form
from wtforms import StringField, PasswordField, BooleanField, SubmitField
from wtforms.validators import Required, Email, Length, Regexp, EqualTo
from wtforms import ValidationError
from ..models import User

# class QuizForm(Form):
# 	

app/quiz/__init__.py
from flask import Blueprint

quiz = Blueprint('quiz', __name__)

from . import views

app/quiz/views.py
from flask import render_template, redirect, request, url_for, flash, jsonify
from . import quiz
from flask_login import login_required, login_user, logout_user, current_user
from ..models import User, Quiz,Score
# from .forms import LoginForm, RegistrationForm
from ..email import send_email
from app import db
import csv
import json


QUESTIONSCORE = 10

@quiz.route('/')
def quizz():
	return redirect(url_for('main.index'))

@quiz.route('/view/<token>', methods = ['GET', 'POST'])
@login_required
def view(token):
	quizId = token.split('-')[0]
	quiz = Quiz.query.filter_by(id = quizId).first()
	
	if quiz is not None:

		score = Score.query.filter_by(giverId = current_user.get_id()).filter_by(quizId = quizId).first()

		if score is not None:
			# if already given
			if request.method == 'POST':
				flash("You can't submit the same test again! You scored " + score.score + ", deal with it!")

			isCreator = True # done to show shareable link thingy
			quizName = quiz.quizName
			questions = list(quiz.questionsIdList)
			numericalScore = score.score
			answers = score.answers

			correctAnswers = []
			for q in questions:
				correctAnswers.append(q['ans'])


			totalScore = len(questions) * QUESTIONSCORE

			lenQuestions = len(questions)
			return render_template('quiz/answers.html', isCreator = isCreator, quizName = quizName, numericalScore = numericalScore, answers = answers, questions = questions, totalScore = totalScore, correctAnswers = correctAnswers, token = token, lenQuestions = lenQuestions)

			# render the same answers

		else:
			if request.method == 'POST':
				# analyse answers here
				questions = list(quiz.questionsIdList)	
				answers = []
				numericalScore = 0
				for i in range(len(questions)):
					print request.form.get(str(i))
					answers.append(request.form.get(str(i)))
					if request.form.get(str(i)) == questions[i]['ans']:
						numericalScore = numericalScore + QUESTIONSCORE

				score = Score()
				score.giverId = current_user.get_id()
				score.quizId = quizId
				score.score = numericalScore
				score.answers = answers

				db.session.add(score)
				db.session.commit()
				# print "here"
				return redirect(url_for('quiz.view', token = token))


			else:
				# render quiz here
				isCreator = False

				quizName = quiz.quizName
				creatorId = quiz.creatorId

				if creatorId == current_user.get_id():
					isCreator = True
				else:
					isCreator = False

				questions = list(quiz.questionsIdList)
				# print questions

				# return redirect(url_for('main.index'))

				return render_template('quiz/quiz.html', isCreator = isCreator, quizName = quizName, questions = questions, token = token, questionsLen = len(questions))


	else:
		flash('Error - 404')
		return redirect(url_for('main.index'))


@quiz.route('/create', methods = ['GET', 'POST'])
@login_required
def createQuiz():
	if current_user.role_id == 2 or current_user.role_id == 3:
		if request.method == 'POST':
			fileCsv = request.files['file']
			csvfile = fileCsv
			reader = csv.DictReader( csvfile)
			

			jsonData = []

			for row in reader:
				jsonData.append(row)

			# print jsonData

			quiz = Quiz()
			quiz.quizName = fileCsv.filename
			quiz.creatorId = current_user.get_id()
			quiz.questionsIdList = jsonData

			db.session.add(quiz)
			db.session.commit()

			token = quiz.generateToken()

			return redirect(url_for('quiz.view', token = token))

		else:
			return render_template('quiz/upload.html')
		# then only allow these actions to occur
		# get questions from excel file
		# create unique form with these questions
	else:
		flash('You are not allowed to create quizzes')
		return redirect(url_for('main.index'))

app/templates/quiz/answers.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %} {{ quizName }} {% endblock %}

{% block page_content %}

{% if isCreator %}

The shareable link for this quiz is : <a href="{{url_for('quiz.quizz', _external=True)}}view/{{ token }}">{{url_for('quiz.quizz', _external=True)}}view/{{ token }}</a>
{% endif %}

<h1> {{ quizName }}</h1>

<h4>You have submitted the quiz!</h4>
<h5> Your score is {{numericalScore}}/{{totalScore}}</h5>

<form>
    <ol>
        {% for i in range(lenQuestions) %}
        <div class="jumbotron">
            <li > {{questions[i].question }} </li>
            <input type='radio' value='{{questions[i].opt1}}' name='{{i}}'>{{questions[i]['opt1']}} </input>
            {% if questions[i]['opt1'] == correctAnswers[i] %}
                    &#10004;
            {% endif %}

            {% if questions[i]['opt1'] == answers[i] %}
                {% if answers[i] != correctAnswers[i] %}
                    &#10007;
                {% endif%}
            {% endif %}

            <input type='radio' value='{{questions[i].opt2}}' name='{{i}}'>{{questions[i]['opt2']}} </input>
            {% if questions[i]['opt2'] == correctAnswers[i] %}
                    &#10004;
            {% endif %}

            {% if questions[i]['opt2'] == answers[i] %}
                {% if answers[i] != correctAnswers[i] %}
                    &#10007;
                {% endif%}
            {% endif %}

            <input type='radio' value='{{questions[i].opt3}}' name='{{i}}'>{{questions[i]['opt3']}} </input>
            {% if questions[i]['opt3'] == correctAnswers[i] %}
                    &#10004;
            {% endif %}

            {% if questions[i]['opt3'] == answers[i] %}
                {% if answers[i] != correctAnswers[i] %}
                    &#10007;
                {% endif%}
            {% endif %}

            <input type='radio' value='{{questions[i].opt4}}' name='{{i}}'>{{questions[i]['opt4']}} </input>
            {% if questions[i]['opt4'] == correctAnswers[i] %}
                    &#10004;
            {% endif %}

            {% if questions[i]['opt4'] == answers[i] %}
                {% if answers[i] != correctAnswers[i] %}
                    &#10007;
                {% endif%}
            {% endif %}
</div>
        {% endfor %}
        
    </ol>
</form>

{% endblock %}

app/templates/quiz/quiz.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %} {{ quizName }} {% endblock %}

{% block page_content %}

{% if isCreator %}
<h3>The shareable link is : {{url_for('quiz.view', token, _external = True)}} </h3>

{% endif %}

<h1> {{ quizName }}</h1>

<form action="{{url_for('quiz.view', token =token)}}" method='POST'>
    <ol>
        {% for i in range(questionsLen) %}
        <div class="jumbotron">
            <li> {{questions[i].question }} </li>
            <input type='radio' value='{{questions[i].opt1}}' name='{{i}}'>{{questions[i]['opt1']}} </input>
            <input type='radio' value='{{questions[i].opt2}}' name='{{i}}'>{{questions[i]['opt2']}} </input>
            <input type='radio' value='{{questions[i].opt3}}' name='{{i}}'>{{questions[i]['opt3']}} </input>
            <input type='radio' value='{{questions[i].opt4}}' name='{{i}}'>{{questions[i]['opt4']}} </input>
        </div>
        {% endfor %}
    </ol>
    <input type="submit" value="submit" />
</form>

{% endblock %}

app/templates/quiz/upload.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}


{% block title %}Ganache - Make Quiz{% endblock %}


{% block page_content %}
<h1>Excel file upload (csv, tsv, csvz, tsvz only)</h1>
    
      <form action = "{{url_for('quiz.createQuiz')}}" method = "POST" 
         enctype = "multipart/form-data">
         <input type = "file" name = "file" />
         <input type = "submit"/>
      </form>

{% endblock %}